import type { Metadata } from "next";
import { Syne } from "next/font/google";
import { ReviewsProvider } from '@/context/reviewsContext';
import ComponentsStatusProvider from "@/context/componentsStatusContext";
import Header from '@/components/Header/Header';
import BookingModal from '@/components/BookingModal/BookingModal';
import MobileBookingButton from '@/components/MobileBookingButton/MobileBookingButton'
import ScrollDownIndicator from '@/components/ScrollDownIndicator/ScrollDownIndicator';
import ScrollProgress from "@/components/ScrollProgress/ScrollProgress";
import Footer from "@/components/Footer/Footer";
import "./globals.css";

// To prevent icons from becoming huge on page refresh
import '@fortawesome/fontawesome-svg-core/styles.css'; // Importa i CSS
import { config } from '@fortawesome/fontawesome-svg-core';
config.autoAddCss = false;

const syne = Syne({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${syne.className} antialiased`}
      >
        <ReviewsProvider>
          <ComponentsStatusProvider>
            <Header />
            <BookingModal />
            <MobileBookingButton />
            <ScrollDownIndicator />
            <ScrollProgress />
            <main
              id="main"
              className="flex flex-col w-full"
            >
              {children}
            </main>
            <Footer />
          </ComponentsStatusProvider>
        </ReviewsProvider>
      </body>
    </html>
  );
}
